// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zegomrbdtatfrwvoyupx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplZ29tcmJkdGF0ZnJ3dm95dXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Mzk5NjcsImV4cCI6MjA1OTMxNTk2N30.ijDLYe188-sndP27BCy6K7FO_tEEQqt8vr8anIqOZ9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);